services:
  animal-spotter-runner:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: animal-spotter-runner
    restart: unless-stopped
    environment:
      RUNNER_URL: "https://github.com/LynnDelaere/animal_spotter"
      RUNNER_NAME: "animal-spotter-runner-1"
      RUNNER_LABELS: "self-hosted,animal-spotter"
      RUNNER_TOKEN: "Fill_in_your_token_here"
    volumes:
      - ./runner-data:/home/runner