name: Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: self-hosted
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Show python version on system
      run: python --version

    - name: Set up venv
      run: python -m venv .venv

    - name: Install deps into venv
      run: |
        .venv/bin/python -m pip install --upgrade pip
        .venv/bin/pip install -r requirements.txt

    - name: Run tests with pytest
      run: |
        .venv/bin/pytest tests --cov=src --cov-report=xml
